### ISSUE TITLE
Custom HOC breaks auto-static-optimization in build

### ISSUE THREAD

**Issue by poeyer** [aralroca/next-translate-plugin#71]
**What version of this package are you using?**
* 2.5.3

**What operating system, Node.js, and npm version?**
* macOs Ventura (13.5.2)
* Node: 18.x

**What happened?**
Using pages 

The plugin checks if the app has a HOC. If you add a custom HOC without `getInitialProps`, the plugin assumes it's a HOC with `getInitialProps`. This makes you opt out of the https://nextjs.org/docs/messages/opt-out-auto-static-optimization because the logic of the Next.js build checks if there is a `getInitialProps` or not.
The `hasHoc` util must check if the app actually has getInitialProps and only return the HOC template if that's the case.

I have this issue with TRPC, you need to have:
`export default trpcHoc.withTRPC(App)`

When SSR: false, it doesn't do `getInitialProps`

**What did you expect to happen?**
* the plugin must not return `getInitialProps` when there isn't one provided in a HOC.

**Are you willing to submit a pull request to fix this bug?**
No

**Comment by aralroca** [comment]
This behavior is because there are some HOC that internally are overwritting the `getInitialProps`. This behavior is documented in the README.md that this is in this way just to avoid issues with HOC. If you know that the HOC is fine, you always can do this workaround to force what loader do you want in your page:

```js
export let getStaticProps = undefined
```

https://github.com/aralroca/next-translate/issues/801#issuecomment-1059800473
